
/**
 **Question given by GEMS Modern Academy during preparation of ISC / ICSE Board Exams**
Bulls and Cows
This game is played with 4 digits. The computer generates a random 4 digit number.
Ensure that the random 4 digit number that is generated by the system has unique digits.
If the digits are not unique, the system should generate another random number. Then
the player should try to guess the number that has been generated by the system. If the
matching digits are in their right positions, they are "bulls" and if they are in different
positions, they are "cows".
Example:
 Number generated by system : 4271
 User’s try : 1234
 Answer: 1 bull and 2 cows. (The bull is "2", the cows are "4" and "1".)
It is proven that any number could be solved within seven turns. 
 */

import java.util.Scanner;

class BullsandCows {
    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);
        System.out.println("Enter your guess");
        String guess = sc.nextLine();
        String secret = String.valueOf(Math.random());
        int countBull = 0;
        int countCow = 0;
        int[] arr1 = new int[10];
        int[] arr2 = new int[10];
        for (int i = 0; i < secret.length(); i++) {
            char c1 = secret.charAt(i);
            char c2 = guess.charAt(i);
            if (c1 == c2)
                countBull++;
            else {
                int n = (c1 - 48);
                arr1[n]++;
                n = (c2 - 48);
                arr2[n]++;
            }
        }
        for (int i = 0; i < 10; i++) {
            countCow += Math.min(arr1[i], arr2[i]);
        }
        System.out.println(countBull + "A" + countCow + "B");
    }
}